-- Mittens Acoustics Module
-- 2D Standing Wave Field Computation for Acoustic Manipulation
--
-- This module implements the standing wave equation for acoustic fields
-- generated by two opposing speakers in the lymph bath.
--
-- Physics:
--   - Superposition of two plane waves (speakers at opposite ends)
--   - Standing wave pattern = constructive/destructive interference
--   - Pressure field: p(x,z,t) = p1(x,z,t) + p2(x,z,t)
--   - Each source: p_i = A * cos(k*dist - ωt + φ_i)
--   where:
--     A = amplitude (Pa)
--     k = wave number (2π/λ)
--     ω = angular frequency (2πf)
--     φ = phase offset (for sweep/control)
--
-- Applications:
--   - Visualize pressure nodes/antinodes
--   - Drive body forces in flow solver
--   - Enable acoustic manipulation of fluid

local Acoustics = {}

-- =============================================================================
-- Configuration Constants
-- =============================================================================

-- Default bath geometry (from lymph_bath.lua, in mm)
Acoustics.DEFAULT_BATH = {
  length = 2000,      -- X dimension (mm)
  width = 600,        -- Y dimension (mm)
  depth = 400,        -- Z dimension (mm)
  center_z = 200,     -- Z position of acoustic sources (mm)
}

-- Default simulation parameters
Acoustics.DEFAULT_PARAMS = {
  frequency = 0.02,        -- Hz (vasomotion-matched)
  amplitude = 100,         -- Pa (pressure amplitude)
  phase_sweep = 0.1,       -- Hz (rate of phase sweep for moving standing wave)
  medium_speed = 1524,     -- m/s (water at 37°C)
}

-- =============================================================================
-- Acoustic Source Definition
-- =============================================================================

--- Create an acoustic point source
-- @param id string Source identifier
-- @param position {x, y, z} Source position (mm)
-- @param amplitude number Pressure amplitude (Pa)
-- @param frequency number Frequency (Hz)
-- @param phase number Initial phase offset (radians, default 0)
-- @return source table
local function AcousticSource(id, position, amplitude, frequency, phase)
  return {
    id = id,
    position = position,
    amplitude = amplitude or 100,
    frequency = frequency or 0.02,
    phase = phase or 0,
    
    -- Derived quantities (computed on demand)
    omega = 2 * math.pi * (frequency or 0.02),              -- Angular frequency (rad/s)
    wavelength = (1524 / (frequency or 0.02)) * 1000,      -- Wavelength (mm)
    wavenumber = 2 * math.pi / ((1524 / (frequency or 0.02)) * 1000),  -- k (1/mm)
  }
end

Acoustics.AcousticSource = AcousticSource

-- =============================================================================
-- 2D Standing Wave Field Computation
-- =============================================================================

--- Compute 2D acoustic pressure field for standing wave configuration
-- @param bath_config Bath geometry (length, width, depth, center_z)
-- @param source_config Acoustic sources (left_source, right_source)
-- @param params Simulation parameters (frequency, amplitude, phase_sweep)
-- @param time Current simulation time (seconds)
-- @param plane_offset Y offset for XZ plane slice (mm, default 0 for center)
-- @return field Grid-based pressure field {x, z, pressure_magnitude, pressure_phase}
local function StandingWaveField(bath_config, source_config, params, time, plane_offset)
  bath_config = bath_config or Acoustics.DEFAULT_BATH
  source_config = source_config or {}
  params = params or Acoustics.DEFAULT_PARAMS
  time = time or 0
  plane_offset = plane_offset or 0
  
  -- Validate inputs
  local frequency = params.frequency or Acoustics.DEFAULT_PARAMS.frequency
  local amplitude = params.amplitude or Acoustics.DEFAULT_PARAMS.amplitude
  local phase_sweep = params.phase_sweep or Acoustics.DEFAULT_PARAMS.phase_sweep
  local medium_speed = params.medium_speed or Acoustics.DEFAULT_PARAMS.medium_speed
  
  -- Compute derived acoustic parameters
  local omega = 2 * math.pi * frequency                      -- Angular frequency (rad/s)
  local wavelength = (medium_speed / frequency) * 1000       -- Wavelength in mm
  local wavenumber = 2 * math.pi / wavelength                -- Wave number k (1/mm)
  
  -- Time-dependent phase sweep (for "moving" the standing wave)
  -- This is how acoustic manipulation works in practice
  local sweep_phase = 2 * math.pi * phase_sweep * time       -- Radians
  
  -- Speaker positions (left/right ends of bath)
  local left_speaker = source_config.left or {
    x = -bath_config.length / 2,
    y = 0,
    z = bath_config.center_z,
    amplitude = amplitude,
    phase = 0,
  }
  
  local right_speaker = source_config.right or {
    x = bath_config.length / 2,
    y = 0,
    z = bath_config.center_z,
    amplitude = amplitude,
    phase = math.pi,  -- 180° out of phase for standing wave
  }
  
  -- Grid parameters for field computation
  local grid_x_points = 81          -- 81 points along X (25mm spacing for 2000mm)
  local grid_z_points = 41          -- 41 points along Z (10mm spacing for 400mm)
  local x_min = -bath_config.length / 2
  local x_max = bath_config.length / 2
  local z_min = 0
  local z_max = bath_config.depth
  
  -- Compute grid step sizes
  local dx = (x_max - x_min) / (grid_x_points - 1)
  local dz = (z_max - z_min) / (grid_z_points - 1)
  
  -- Initialize field data structure
  local field = {
    _type = "acoustic_field",
    time = time,
    frequency = frequency,
    amplitude = amplitude,
    wavelength = wavelength,
    wavenumber = wavenumber,
    omega = omega,
    phase_sweep = phase_sweep,
    sweep_phase = sweep_phase,
    
    -- Grid parameters
    grid_x_points = grid_x_points,
    grid_z_points = grid_z_points,
    x_min = x_min,
    x_max = x_max,
    z_min = z_min,
    z_max = z_max,
    dx = dx,
    dz = dz,
    plane_offset = plane_offset,
    
    -- Pressure field data: [x_idx][z_idx] = {pressure, phase}
    pressure = {},      -- Magnitude of pressure
    phase = {},         -- Phase angle
    
    -- Statistics
    max_pressure = 0,
    min_pressure = 0,
    nodes = {},         -- Pressure node locations (zero crossings)
    antinodes = {},     -- Pressure antinode locations (maxima)
  }
  
  -- =========================================================================
  -- COMPUTATION: Superposition of two plane waves
  -- =========================================================================
  
  -- Compute pressure at each grid point
  for x_idx = 1, grid_x_points do
    field.pressure[x_idx] = {}
    field.phase[x_idx] = {}
    
    local x = x_min + (x_idx - 1) * dx
    
    for z_idx = 1, grid_z_points do
      local z = z_min + (z_idx - 1) * dz
      
      -- Distance from left speaker
      local r_left = math.sqrt(
        (x - left_speaker.x)^2 +
        (plane_offset - left_speaker.y)^2 +
        (z - left_speaker.z)^2
      )
      
      -- Distance from right speaker
      local r_right = math.sqrt(
        (x - right_speaker.x)^2 +
        (plane_offset - right_speaker.y)^2 +
        (z - right_speaker.z)^2
      )
      
      -- Prevent singularities at source positions
      r_left = math.max(r_left, 0.1)
      r_right = math.max(r_right, 0.1)
      
      -- ===================================================================
      -- Pressure from left speaker: p_L = (A/r) * cos(k*r - ωt + φ_L)
      -- ===================================================================
      -- For acoustic radiation, pressure amplitude decreases with distance
      -- as 1/r (spherical spreading loss)
      local p_left_amp = (left_speaker.amplitude / r_left) * 1000  -- Scale: 1/r converts mm to dimensionless
      local p_left_phase = wavenumber * r_left - omega * time + left_speaker.phase + sweep_phase
      local p_left = p_left_amp * math.cos(p_left_phase)
      
      -- ===================================================================
      -- Pressure from right speaker: p_R = (A/r) * cos(k*r - ωt + φ_R)
      -- ===================================================================
      local p_right_amp = (right_speaker.amplitude / r_right) * 1000
      local p_right_phase = wavenumber * r_right - omega * time + right_speaker.phase + sweep_phase
      local p_right = p_right_amp * math.cos(p_right_phase)
      
      -- ===================================================================
      -- SUPERPOSITION: Total pressure = p_left + p_right
      -- ===================================================================
      -- This creates the standing wave pattern:
      -- - Constructive interference → pressure antinodes (pressure antinodes)
      -- - Destructive interference → pressure nodes (zero crossing)
      local p_total = p_left + p_right
      
      -- Store pressure magnitude and phase
      field.pressure[x_idx][z_idx] = math.abs(p_total)
      
      -- Phase angle (atan2 handles quadrant correctly)
      local phase_total = math.atan2(
        p_left_amp * math.sin(p_left_phase) + p_right_amp * math.sin(p_right_phase),
        p_total
      )
      field.phase[x_idx][z_idx] = phase_total
      
      -- Track min/max pressure
      if field.pressure[x_idx][z_idx] > field.max_pressure then
        field.max_pressure = field.pressure[x_idx][z_idx]
      end
    end
  end
  
  -- =========================================================================
  -- POST-PROCESSING: Identify nodes and antinodes
  -- =========================================================================
  
  for x_idx = 2, grid_x_points - 1 do
    local x = x_min + (x_idx - 1) * dx
    
    for z_idx = 2, grid_z_points - 1 do
      local z = z_min + (z_idx - 1) * dz
      
      local p_current = field.pressure[x_idx][z_idx]
      local p_left = field.pressure[x_idx - 1][z_idx]
      local p_right = field.pressure[x_idx + 1][z_idx]
      local p_up = field.pressure[x_idx][z_idx + 1]
      local p_down = field.pressure[x_idx][z_idx - 1]
      
      -- Check if this is a local maximum (antinode)
      if p_current >= p_left and p_current >= p_right and
         p_current >= p_up and p_current >= p_down and
         p_current > 0.1 * field.max_pressure then
        table.insert(field.antinodes, {x = x, z = z, pressure = p_current})
      end
      
      -- Check if this is a local minimum/node
      if p_current <= p_left and p_current <= p_right and
         p_current <= p_up and p_current <= p_down and
         p_current < 0.1 * field.max_pressure then
        table.insert(field.nodes, {x = x, z = z, pressure = p_current})
      end
    end
  end
  
  -- =========================================================================
  -- Methods for field analysis and visualization
  -- =========================================================================
  
  setmetatable(field, {__index = {
    -- Get pressure at arbitrary point (with interpolation)
    pressure_at = function(self, x, z)
      -- Linear interpolation within grid
      local x_frac = (x - self.x_min) / (self.x_max - self.x_min)
      local z_frac = (z - self.z_min) / (self.z_max - self.z_min)
      
      -- Clamp to grid bounds
      x_frac = math.max(0, math.min(1, x_frac))
      z_frac = math.max(0, math.min(1, z_frac))
      
      -- Convert to grid indices
      local x_idx = x_frac * (self.grid_x_points - 1) + 1
      local z_idx = z_frac * (self.grid_z_points - 1) + 1
      
      -- Bilinear interpolation
      local x_low = math.floor(x_idx)
      local z_low = math.floor(z_idx)
      local x_high = math.min(self.grid_x_points, x_low + 1)
      local z_high = math.min(self.grid_z_points, z_low + 1)
      
      local dx_weight = x_idx - x_low
      local dz_weight = z_idx - z_low
      
      local p00 = self.pressure[x_low][z_low] or 0
      local p10 = self.pressure[x_high][z_low] or 0
      local p01 = self.pressure[x_low][z_high] or 0
      local p11 = self.pressure[x_high][z_high] or 0
      
      local p_interp = 
        p00 * (1 - dx_weight) * (1 - dz_weight) +
        p10 * dx_weight * (1 - dz_weight) +
        p01 * (1 - dx_weight) * dz_weight +
        p11 * dx_weight * dz_weight
      
      return p_interp
    end,
    
    -- Normalize pressure for visualization (0-1)
    normalized_pressure = function(self, x, z)
      local p = self:pressure_at(x, z)
      if self.max_pressure > 0 then
        return p / self.max_pressure
      else
        return 0
      end
    end,
    
    -- Compute pressure gradient (for force field)
    gradient = function(self, x, z)
      local eps = self.dx * 0.5
      local px_plus = self:pressure_at(x + eps, z)
      local px_minus = self:pressure_at(x - eps, z)
      local pz_plus = self:pressure_at(x, z + eps)
      local pz_minus = self:pressure_at(x, z - eps)
      
      return {
        x = (px_plus - px_minus) / (2 * eps),
        z = (pz_plus - pz_minus) / (2 * eps),
      }
    end,
    
    -- Get field statistics
    statistics = function(self)
      return {
        max_pressure = self.max_pressure,
        min_pressure = self.min_pressure,
        node_count = #self.nodes,
        antinode_count = #self.antinodes,
        frequency = self.frequency,
        wavelength = self.wavelength,
        time = self.time,
      }
    end,
    
    -- Serialize for transmission/storage
    serialize = function(self)
      -- Note: pressure grid can be large, so we store summary data
      return {
        type = "acoustic_field",
        time = self.time,
        frequency = self.frequency,
        amplitude = self.amplitude,
        wavelength = self.wavelength,
        wavenumber = self.wavenumber,
        omega = self.omega,
        phase_sweep = self.phase_sweep,
        sweep_phase = self.sweep_phase,
        max_pressure = self.max_pressure,
        node_count = #self.nodes,
        antinode_count = #self.antinodes,
      }
    end,
  }})
  
  return field
end

Acoustics.StandingWaveField = StandingWaveField

-- =============================================================================
-- Integration with Simulation Engine
-- =============================================================================

--- Extend the simulation engine with acoustic field computation
-- @param sim SimulationEngine (from stdlib.simulation)
-- @param acoustic_config Acoustic configuration
-- @return Modified simulation engine with acoustic hooks
local function AcousticSimulation(sim, acoustic_config)
  acoustic_config = acoustic_config or {}
  
  -- Extract or use defaults
  local bath_config = acoustic_config.bath or Acoustics.DEFAULT_BATH
  local source_config = acoustic_config.sources or {}
  local params = acoustic_config.params or Acoustics.DEFAULT_PARAMS
  
  -- Initialize acoustic field in simulation state
  local acoustic_field = StandingWaveField(bath_config, source_config, params, 0)
  
  if sim.state then
    sim.state.acoustic_field = acoustic_field
  end
  
  -- Add acoustic update hook to simulation stepping
  local original_step = sim.step
  sim.step = function(self)
    -- Step the simulation normally
    original_step(self)
    
    -- Update acoustic field with current time
    local current_time = self.state.time
    self.state.acoustic_field = StandingWaveField(bath_config, source_config, params, current_time)
    
    return self
  end
  
  -- Expose acoustic field access
  sim.get_acoustic_field = function(self)
    return self.state.acoustic_field
  end
  
  return sim
end

Acoustics.AcousticSimulation = AcousticSimulation

-- =============================================================================
-- Visualization Support Functions
-- =============================================================================

--- Convert acoustic pressure to RGB color for visualization
-- Pressure antinodes → red (constructive interference)
-- Pressure nodes → blue (destructive interference)
-- @param pressure_normalized Normalized pressure (0-1)
-- @return {r, g, b, a} RGBA color
local function PressureToColor(pressure_normalized)
  -- Clamp to valid range
  pressure_normalized = math.max(0, math.min(1, pressure_normalized))
  
  -- Red = high pressure (antinodes)
  -- Blue = low pressure (nodes)
  -- Smooth interpolation with white at maximum
  
  local r = pressure_normalized
  local g = 0.2 * (1 - math.abs(pressure_normalized - 0.5) * 2)  -- Peak at 0.5
  local b = 1 - pressure_normalized
  local a = 0.6  -- Slightly transparent for overlay
  
  return {r, g, b, a}
end

Acoustics.PressureToColor = PressureToColor

-- =============================================================================
-- Convenience Functions
-- =============================================================================

--- Create a complete acoustic setup with sensible defaults
-- @param bath_length Bath length (mm)
-- @param frequency Driving frequency (Hz)
-- @param amplitude Pressure amplitude (Pa)
-- @return Acoustic configuration table
function Acoustics.create_default_field(bath_length, frequency, amplitude)
  bath_length = bath_length or Acoustics.DEFAULT_BATH.length
  frequency = frequency or Acoustics.DEFAULT_PARAMS.frequency
  amplitude = amplitude or Acoustics.DEFAULT_PARAMS.amplitude
  
  local bath_config = {
    length = bath_length,
    width = Acoustics.DEFAULT_BATH.width,
    depth = Acoustics.DEFAULT_BATH.depth,
    center_z = Acoustics.DEFAULT_BATH.center_z,
  }
  
  local params = {
    frequency = frequency,
    amplitude = amplitude,
    phase_sweep = 0.1,
    medium_speed = 1524,
  }
  
  return StandingWaveField(bath_config, {}, params, 0)
end

-- =============================================================================
-- Export API
-- =============================================================================

return Acoustics
